import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useEffect } from 'react';


export default function Home() {
  const [inputFilter,setInputFilter] = React.useState();
  const [data,setData] = React.useState([]);
  const handlerInputFilter = (e) =>{
    setInputFilter(e.target.value);
  }

  const getData = async () =>{
    const res = await fetch('https://api.publicapis.org/categories');
    const data = await res.json();
    setData(data);
  }
  
  useEffect(() =>{
    getData();
  },[]);

  useEffect(() =>{
    filter(inputFilter,data);
  },[inputFilter]);


  function filter(input, data){
    if(input!=null && input.length){
      const filterResult = [];
      var filter = input.toUpperCase();
      for(var i = 0; i < data.length; i++){
        if(data[i].toUpperCase().indexOf(filter) > -1){
            filterResult.push(data[i]);
        }
      }     
      setData(filterResult);
    }else getData();
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Change input to filter the data
        </h1>
   
          <div className="m-3">
            <input type="text" className="form-control" onChange={(e)=> handlerInputFilter(e)} />
          </div>
          {inputFilter}

        <div className={styles.table}>
        <table className="table table-striped">
            <thead className="thead">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Categories</th>
              </tr>
            </thead>
            <tbody>
               {data.length ? data.map((el,index)=>{
                  return(
                    <>
                      <tr>
                        <th scope="row">{index+1}</th>
                        <td>{el}</td>
                      </tr>
                    </>
                  )
                }):
                  <tr>
                    <th scope="row">"{inputFilter}"</th>
                    <td>is not found</td>
                  </tr>
                }
            </tbody>
          </table>
        </div>
      </main>
    </div>
  )
}
